// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGIjGPZqXyv-5aCp9rQzW-Pv9UPYBhnU',
    appId: '1:896673043508:web:a52e3dd8b33ef17bf7a661',
    messagingSenderId: '896673043508',
    projectId: 'carrental-7dc19',
    authDomain: 'carrental-7dc19.firebaseapp.com',
    storageBucket: 'carrental-7dc19.firebasestorage.app',
    measurementId: 'G-37DGXW2028',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuE3mGaUJgS8JAu65vIDHoXjcNC1LRZDQ',
    appId: '1:896673043508:android:8041720d5f4ccd0bf7a661',
    messagingSenderId: '896673043508',
    projectId: 'carrental-7dc19',
    storageBucket: 'carrental-7dc19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8t6MrbeY88N02Jsy1QVXCpL2bct0zX9k',
    appId: '1:896673043508:ios:709483841eb911d7f7a661',
    messagingSenderId: '896673043508',
    projectId: 'carrental-7dc19',
    storageBucket: 'carrental-7dc19.firebasestorage.app',
    iosBundleId: 'com.example.carrentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8t6MrbeY88N02Jsy1QVXCpL2bct0zX9k',
    appId: '1:896673043508:ios:709483841eb911d7f7a661',
    messagingSenderId: '896673043508',
    projectId: 'carrental-7dc19',
    storageBucket: 'carrental-7dc19.firebasestorage.app',
    iosBundleId: 'com.example.carrentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChGIjGPZqXyv-5aCp9rQzW-Pv9UPYBhnU',
    appId: '1:896673043508:web:aa90067fe887da93f7a661',
    messagingSenderId: '896673043508',
    projectId: 'carrental-7dc19',
    authDomain: 'carrental-7dc19.firebaseapp.com',
    storageBucket: 'carrental-7dc19.firebasestorage.app',
    measurementId: 'G-KNCMYED7LD',
  );
}
